spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lightstick?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: lightstick
    password: lightstick!!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8070

socketio:
  server:
    hostname: 192.168.0.9
    port: 8071